### ISSUE TITLE
Add --init-db flag to create db if it does not exist

### ISSUE THREAD

**Issue by Leopere** [lbryio/reflector.go#20]
- [ ] add `--init-db` flag
- [ ] if flag is set and db does not exist, create the db using the schema at https://github.com/lbryio/reflector.go/blob/master/db/db.go#L417-L452

**Comment by lyoshenka** [comment]
i agree. i didnt bother with this because the schema rarely changes

**Comment by lyoshenka** [comment]
i didnt bother with this because the schema rarely changes. if you do make this happen on launch, i suggest adding a flag like `--init-db` to make sure the user knows and intends this behavior.

**Comment by chron0** [comment]
Also, giving my 2 cents here... Wouldnt something like leveldb have made much more sense so we wouldnt have to run, monitor and secure a separate server process (mysql)? I'd love to hack around leveldb together with the reflector, but that doesnt make much sense to me as lond as S3 is a requirement.

**Comment by lyoshenka** [comment]
The short answer is that neither s3 nor mysql are requirements. Different backends are supported and new ones (like leveldb) are easy to add.

There's a longer discussion here: https://github.com/lbryio/reflector.go/issues/28#issuecomment-640775545
