### ISSUE TITLE
What are the basic invocation flags required to start Reflector or at the very least a default configuration example

### ISSUE THREAD

**Issue by chamunks** [lbryio/reflector.go#21]
A oneliner in the title because I'm awful like that.

**Comment by lyoshenka** [comment]
Its `/path/to/binary reflector --conf=/path/to/conf`. There's a sample conf file here https://github.com/lbryio/reflector.go/blob/master/config.tmpl. You'll need an s3 bucket and a mysql database set up.

**Comment by lyoshenka** [comment]
If you want to see the entry point in the code, look at https://github.com/lbryio/reflector.go/blob/master/cmd/reflector.go. This is where the execution starts (more or less).
