### ISSUE TITLE
Ensure that all components use the stopper pattern

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/reflector.go#3]
- every component should have the following methods: 
  - `New` creates and configures the component. it should allocate any necessary slices, maps, etc.
  - `Start` or `Connect` starts the component, connects it to the network, runs any goroutines, etc.
  - `Shutdown` stops goroutines, disconnects and shuts down the component. it should block until the internals have shut down correctly
- every component should have a *stopOnce.Stopper that controls the shutdown process.
- all goroutines should stop.Add() and stop.Done() to signal their start/stop
- all goroutines should exit cleanly and as soon as possible after stop.Stop() is called

**Comment by tiger5226** [comment]
Addressed with https://github.com/lbryio/reflector.go/pull/11

**Comment by tiger5226** [comment]
Addressed with #11
